# -*- coding: utf-8 -*-
"""Assignment 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1byZQbAJ_vgxDgJ-7iC2AqSWN_mwf6wos
"""

!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

!unzip orders.csv.zip

import pandas as pd
df=pd.read_csv('orders.csv')
df

df.head()

df.tail()

df.info()



df.describe()

df.isnull()

df.isnull().sum()

missing_ship_mode = df[df['Ship Mode'].isnull()]
print(missing_ship_mode)

missing_ship_mode = df[df['Ship Mode'].isnull()]
print(missing_ship_mode)

df.isnull().sum()

df.rename(columns={'Order Id': 'order_id'}, inplace=True)
df.rename(columns={'Order Date': 'order_date'}, inplace=True)
df.rename(columns={'Ship Mode': 'ship_mode'}, inplace=True)
df.rename(columns={'Postal Code': 'postal_code'}, inplace=True)
df.rename(columns={'Sub Category': 'sub_category'}, inplace=True)
df.rename(columns={'Segment': 'segment'}, inplace=True)
df.rename(columns={'Region': 'region'}, inplace=True)
df.rename(columns={'Category': 'category'}, inplace=True)
df.rename(columns={'Product Id ': 'product_id'}, inplace=True)
df.rename(columns={'Sales': 'sales'}, inplace=True)
df.rename(columns={'Quantity': 'quantity'}, inplace=True)
df.rename(columns={'Discount Percent': 'discount_percent'}, inplace=True)
df.rename(columns={'cost price': 'cost_price'}, inplace=True)
df.rename(columns={'List Price': 'list_price'}, inplace=True)
df.rename(columns={'Country': 'country'}, inplace=True)
df.rename(columns={'State': 'state'}, inplace=True)
df

df.rename(columns={'Product Id': 'product_id'}, inplace=True)
df

# Remove trailing spaces from a specific column
df['product_id'] = df['product_id'].str.rstrip()
df['product_id']

df['product_id'] = df['product_id'].str.rstrip()
df['product_id']

df.applymap(lambda x: x.rstrip() if isinstance(x, str) else x)
df

# Calculate the Discount column
df['discount'] = df['list_price'] * (df['discount_percent'] / 100)

# Calculate the Sale Price column
df['sale_price'] = df['list_price'] - df['discount']

# Calculate the Profit column
df['profit'] = df['sale_price'] - df['cost_price']

# Display the updated DataFrame
(df)

df.rename(columns={'Profit': 'profit'}, inplace=True)
df.rename(columns={'Sale Price': 'sale_price'}, inplace=True)
df.rename(columns={'Discount': 'discount'}, inplace=True)
df

df.loc[:, ~df.columns.duplicated(keep='first')]
df

df.drop_duplicates(inplace=True)
df

df

df.to_csv("retailorders.csv")

